#!/bin/bash

##################################################################
#
# Copytest - A simple file copy transfer speed testing tool
# =========================================================
#
# Uses cp, rsync and dd to provide an analysis of the various
# methods of copying a file from a source and destination location.
# dd is used with various block sizes to find the optimal transfer
# size for the combination of filesystems you are testing.
#
# Requires:
# - bash
# - cp
# - rsync
# - dd
# - bc
# - gnuplot (optional)
#
# Produces a CSV data file of the test results, optionally if you
# have gnuplot installed the output can be plotted directly into
# a chart.
#
# To run, 'source' this file and follow the instructions displayed.
#
#################################################################
#
# See: https://github.com/megatron-uk/Copytest
# For licensing information, see: LICENSE
#
##################################################################


export COUNTSIZE=2000					# Size of the test file, in megabytes
export TESTDATE=`date +%y%m%d_%H%M`		# Timestamp
export TIMEFORMAT=%R					# Control the output of the 'time' command
export RESULTS="copytest.csv"			# Where CSV output goes
export ERRORS="copytest.err"			# Where STDERR messages go
export CHART="copytest.png"				# Name of chart graphic
export CHART_X=1024						# gnuplot chart x res
export CHART_Y=800						# gnuplot chart y res
export SLEEPTIME=5						# How long to pause between tests/test iterations
export GNUPLOT=0						# Do we have gnuplot
export TEST_COL_START=4					# Which column contains the first test data
export TEST_COL_END=16					# Which column contains the last test data


# From: https://stackoverflow.com/questions/2683279/how-to-detect-if-a-script-is-being-sourced	
(return 0 2>/dev/null) && SOURCED=1 || SOURCED=0
	
create_headers() {
	# CSV Header
	HEADER="Copy Task,Date,File size (MBytes),cp,rsync,dd bs=512,dd bs=8k,dd bs=16k,dd bs=32k,dd bs=64k,dd bs=128k,dd bs=256k,dd bs=512k,dd bs=1024k,dd bs=2048k,dd bs=4096k"
	
	echo "Creating CSV File"
	echo "================="
	if [ -f "$RESULTS" ]
	then
		if [ -s "$RESULTS" ]
		then
			# No-op; results exists
			echo "- Ok: Reused existing CSV results file '$RESULTS'"
			echo ""
		else
			# Write headers
			echo "$HEADER" > $RESULTS
			if [ "$?" = "0" ]
			then
				echo "- Ok: Created CSV file '$RESULTS'"
			else
				echo "- Error: Unable to create CSV results file '$RESULTS'"
				return 1
			fi
			echo ""
		fi
	else
		# Create CSV file and write headers
		echo "$HEADER" > $RESULTS
		if [ "$?" = "0" ]
		then
			echo "- Ok: Wrote CSV headers to file '$RESULTS'"
		else
			echo "- Error: Unable to create CSV results file '$RESULTS'"
			return 1
		fi
		echo ""
	fi
}

create_testfile() {
	# Re-use a test file if one already exists
	echo "Creating Output File"
	echo "===================="
	
	if [ -s "$SRC" ]
	then
		echo "Reusing $SRC"
		echo ""
	else
		echo "Creating $SRC ... please wait ... "
		SPEED=`{ time dd if=/dev/random of=$SRC bs=1M count=$COUNTSIZE >/dev/null 2>>$ERRORS; } 2>&1`
		if [ "$?" != "0" ]
        then
            echo ""
			echo "- Error creating $SRC ..."
            cat $ERRORS
            return 1
        fi
		sleep $SLEEPTIME
		sync $SRC
		SPEED=`echo "$SRC_BYTES / $SPEED / 1024 / 1024" | bc`
		echo "- Ok: Created from /dev/random at $SPEED MB/s"
		echo ""
	fi
}

create_chart_single() {
	# Create a chart using a single testing data result line
	echo "Using Single Result Chart"
	echo "========================="
	
	# Read data line from result csv
	PLOTFILE=`mktemp`
	PLOTDATA=`mktemp`
	
	# Extract headers
	echo "Extracting headers and cell values..."
	l=`cat $RESULTS | grep "Copy Task"`
	
	DATA_TITLE=`cat $RESULTS | grep -v ^"Copy Task" | awk -F, '{print $1}'`
	# Test columns 4-16 inclusive
	# Get test names
	TEST1_LABEL=`echo "$l" | awk -F, '{print $4}'`
	TEST1_DATA=`cat $RESULTS | grep -v ^"Copy Task" | awk -F, '{print $4}'`
	
	TEST2_LABEL=`echo "$l" | awk -F, '{print $5}'`
	TEST2_DATA=`cat $RESULTS | grep -v ^"Copy Task" | awk -F, '{print $5}'`
	
	TEST3_LABEL=`echo "$l" | awk -F, '{print $6}'`
	TEST3_DATA=`cat $RESULTS | grep -v ^"Copy Task" | awk -F, '{print $6}'`
	
	TEST4_LABEL=`echo "$l" | awk -F, '{print $7}'`
	TEST4_DATA=`cat $RESULTS | grep -v ^"Copy Task" | awk -F, '{print $7}'`
	
	TEST5_LABEL=`echo "$l" | awk -F, '{print $8}'`
	TEST5_DATA=`cat $RESULTS | grep -v ^"Copy Task" | awk -F, '{print $8}'`
	
	TEST6_LABEL=`echo "$l" | awk -F, '{print $9}'`
	TEST6_DATA=`cat $RESULTS | grep -v ^"Copy Task" | awk -F, '{print $9}'`
	
	TEST7_LABEL=`echo "$l" | awk -F, '{print $10}'`
	TEST7_DATA=`cat $RESULTS | grep -v ^"Copy Task" | awk -F, '{print $10}'`
	
	TEST8_LABEL=`echo "$l" | awk -F, '{print $11}'`
	TEST8_DATA=`cat $RESULTS | grep -v ^"Copy Task" | awk -F, '{print $11}'`
	
	TEST9_LABEL=`echo "$l" | awk -F, '{print $12}'`
	TEST9_DATA=`cat $RESULTS | grep -v ^"Copy Task" | awk -F, '{print $12}'`
	
	TEST10_LABEL=`echo "$l" | awk -F, '{print $13}'`
	TEST10_DATA=`cat $RESULTS | grep -v ^"Copy Task" | awk -F, '{print $13}'`
	
	TEST11_LABEL=`echo "$l" | awk -F, '{print $14}'`
	TEST11_DATA=`cat $RESULTS | grep -v ^"Copy Task" | awk -F, '{print $14}'`
	
	TEST12_LABEL=`echo "$l" | awk -F, '{print $15}'`
	TEST12_DATA=`cat $RESULTS | grep -v ^"Copy Task" | awk -F, '{print $15}'`
	
	TEST13_LABEL=`echo "$l" | awk -F, '{print $16}'`
	TEST13_DATA=`cat $RESULTS | grep -v ^"Copy Task" | awk -F, '{print $16}'`	
	
	# Write test headers and cell values to plot data file
	# Data file looks like
	# TEST TEST_NAME
	# COPY_METHOD COPY1_VALUE
	# COPY2_METHOD COPY2_VALUE
	#...
	# COPYN_METHOD COPYN_VALUE
	echo "TEST \"$DATA_TITLE\"" > $PLOTDATA
	echo "\"$TEST1_LABEL\" $TEST1_DATA" >> $PLOTDATA
	echo "\"$TEST2_LABEL\" $TEST2_DATA" >> $PLOTDATA
	echo "\"$TEST3_LABEL\" $TEST3_DATA" >> $PLOTDATA
	echo "\"$TEST4_LABEL\" $TEST4_DATA" >> $PLOTDATA
	echo "\"$TEST5_LABEL\" $TEST5_DATA" >> $PLOTDATA
	echo "\"$TEST6_LABEL\" $TEST6_DATA" >> $PLOTDATA
	echo "\"$TEST7_LABEL\" $TEST7_DATA" >> $PLOTDATA
	echo "\"$TEST8_LABEL\" $TEST8_DATA" >> $PLOTDATA
	echo "\"$TEST9_LABEL\" $TEST9_DATA" >> $PLOTDATA
	echo "\"$TEST10_LABEL\" $TEST10_DATA" >> $PLOTDATA
	echo "\"$TEST11_LABEL\" $TEST11_DATA" >> $PLOTDATA
	echo "\"$TEST12_LABEL\" $TEST12_DATA" >> $PLOTDATA
	echo "\"$TEST13_LABEL\" $TEST13_DATA" >> $PLOTDATA
	echo "- Ok"
	
	# gnuplot instructions
	echo ""
	echo "Generating plot script..."
	echo "# Plotfile for Copytest result data"								> $PLOTFILE
	echo "set terminal pngcairo enhanced font \"arial,12\" fontscale 1.0 size $CHART_X, $CHART_Y" >> $PLOTFILE
	echo "set colorbox vertical origin screen 0.9, 0.2 size screen 0.05, 0.6 front  noinvert bdefault" >> $PLOTFILE
	echo "set output '$CHART'"												>> $PLOTFILE
	echo 'set title "Copytest - Filesystem Benchmark Results"' 				>> $PLOTFILE
	echo 'set style data linespoints' 										>> $PLOTFILE
	echo 'set ylabel "MBytes/sec"' 											>> $PLOTFILE
	echo 'set xlabel "Copy method"' 										>> $PLOTFILE
	echo 'set yrange [0:*]' 												>> $PLOTFILE
	echo 'set key autotitle columnhead' 									>> $PLOTFILE
	echo 'set xtics rotate'													>> $PLOTFILE
	echo "plot '$PLOTDATA' using 2:xticlabel(1)" 							>> $PLOTFILE
	echo "#" 																>> $PLOTFILE
	echo "- Ok"
	
	echo ""
	echo "Running gnuplot..."
	gnuplot < $PLOTFILE
	if [ "$?" = "0" ]
	then
		echo "- Ok"
	else
		echo "- Error: Call to gnuplot returned an error"
	fi
	
	echo ""
	echo "Cleaning up"
	echo "==========="
	rm -f -v $PLOTFILE
	rm -f -v $PLOTDATA
	echo ""
}

get_test_average() {
	# Returns the average for a field, summed from all results for a given test
	# $1 == name of test
	# $2 == index of field
	
	# Array is indexed from 0, but the awk field needs to be from 1
	let field_id=($2 + 1)
	lines=0
	total_v=0
	v=0
	average_v=0
	while read v
	do
		let total_v=($total_v + $v) 
		let lines=($lines + 1)
	done <<< "`cat $RESULTS | grep ^"$1," |  cut -d',' -f ${TEST_COL_START}-${TEST_COL_END} | awk -F, '{print $'$field_id'}'`"
	average_v=`echo "$total_v / $lines" | bc -l`
	echo $average_v
}

get_test_range() {
	# Returns the range for a given field, for a given test
	# $1 == name of test
	# $2 == index of field
	
	# Array is indexed from 0, but the awk field needs to be from 1
	let field_id=($2 + 1)
	min_v=9999999
	max_v=0
	range_v=0
	while read v
	do
		if [ "$v" -gt "$max_v" ]
		then
			max_v=$v
		fi
		
		if [ "$v" -lt "$min_v" ]
		then
			min_v=$v
		fi
	done <<< "`cat $RESULTS | grep ^"$1," |  cut -d',' -f ${TEST_COL_START}-${TEST_COL_END} | awk -F, '{print $'$field_id'}'`"
	let range_v=($max_v - $min_v)
	
	# Do not allow negative ranges
	if [ "$range_v" -lt 0 ]
	then
		range_v=0
	fi
	echo $range_v
}

create_chart_multi() {
	# Create a chart using a multiple testing data result lines
	echo "Using Multi-Result Chart"
	echo "========================"
	
	PLOTFILE=`mktemp`
	PLOTDATA=`mktemp`
	
	# TEST TEST_NAME
	# COPY_METHOD1 VALUE1_AVG VALUE1_RANGE
	# COPY_METHOD2 VALUE1_AVG VALUE2_RANGE
	# ...
	# COPY_METHODN VALUEN_AVG VALUEN_RANGE
	
	# Array of all unique test names
	export TEST_NAMES=()
	export TEST_FIELD_NAMES=()
	
	##############################################################################
	# Get test names from the CSV
	##############################################################################
	echo ""
	echo "Extract test names..."
	while read TEST_NAME
	do
		TEST_NAMES+=( "$TEST_NAME" )
		
	done <<< "`cat $RESULTS | grep -v ^'Copy Task' | awk -F, '{print $1}' | sort | uniq`"
	echo "- Ok: ${#TEST_NAMES[@]} tests"
	echo 
	
	##############################################################################
	# Get field names from the CSV
	##############################################################################
	echo ""
	echo "Extract field names..."
	while read TEST_FIELD_NAME
	do
		TEST_FIELD_NAMES+=( "$TEST_FIELD_NAME" )	
	done <<< "`cat $RESULTS | grep ^'Copy Task' | cut -d',' -f ${TEST_COL_START}-${TEST_COL_END} | sed 's/,/\n/g'`"
	echo "- Ok: ${#TEST_FIELD_NAMES[@]} fields"
	
	##############################################################################
	# For each test, determine if it is a single or multi-result type, and 
	# extract all relevant field values
	##############################################################################
	echo ""
	echo "Check test result type..."
	for i in ${!TEST_NAMES[@]}
	do
		TEST_NAME=${TEST_NAMES[$i]}
		
		# Is this test a single line or multi?
		TEST_LINES=`grep ^"$TEST_NAME," $RESULTS | wc -l | awk '{print $1}'`
		if [ "$TEST_LINES" = "1" ]
		then
			# Single line of data for this test
			echo "- [$i] Single result	: '$TEST_NAME'"
			IS_SINGLE_RESULT=1
		else
			# More than one line of data for this test
			echo "- [$i] Multiple results	: '$TEST_NAME'"
			IS_SINGLE_RESULT=0
		fi
		
		# If single, find the row for this test name and read all field values
		if [ "$IS_SINGLE_RESULT" = "1" ]
		then
			TEST_FIELD_VALUES=()
			while read TEST_FIELD_VALUE
			do
				TEST_FIELD_VALUES+=( "$TEST_FIELD_VALUE" )
				
			done <<< "`cat $RESULTS | grep ^"$TEST_NAME," | cut -d',' -f ${TEST_COL_START}-${TEST_COL_END} | sed 's/,/\n/g'`"
			
			# Check we have the same number of values as we have fields
			if [ "${#TEST_FIELD_VALUES[@]}" = "${#TEST_FIELD_NAMES[@]}" ]
			then
				echo "-- Ok: Single result, ${#TEST_FIELD_VALUES[@]} values"
			else
				echo "-- Error: Single result, ${#TEST_FIELD_VALUES[@]} values, should be ${#TEST_FIELD_NAMES[@]}"
				return 1
			fi
			
			# Write this test result to the Copytest gnuplot .dat file
			# The error range for this result set is zero, since we only have one result
			echo "TEST \"$TEST_NAME\"" >> $PLOTDATA
			for f in ${!TEST_FIELD_NAMES[@]}
			do
				TEST_FIELD_NAME=${TEST_FIELD_NAMES[$f]}
				TEST_FIELD_VALUE=${TEST_FIELD_VALUES[$f]}
				echo "\"$TEST_FIELD_NAME\" $TEST_FIELD_VALUE 0" >> $PLOTDATA
			done
			echo "" >> $PLOTDATA
			echo "" >> $PLOTDATA
		fi
		
		# If multi, loop over all rows for this test name, read all field values and calculate averages and error ranges
		if [ "$IS_SINGLE_RESULT" = "0" ]
		then
			
			TEST_FIELD_VALUES=()
			while read TEST_FIELD_VALUE
			do
				TEST_FIELD_VALUES+=( "$TEST_FIELD_VALUE" )
			done <<< "`cat $RESULTS | grep ^"$TEST_NAME," | cut -d',' -f ${TEST_COL_START}-${TEST_COL_END} | sed 's/,/\n/g'`"
			
			# Check we have the same number of values as we have fields
			# if we have multiple rows for this test, it should be: lines * fields = total number of values
			let TOTAL_VALUES=(${#TEST_FIELD_NAMES[@]} * $TEST_LINES)
			echo "${#TEST_FIELD_VALUES[@]} $TOTAL_VALUES"
			if [ "${#TEST_FIELD_VALUES[@]}" = "$TOTAL_VALUES" ]
			then
				echo "-- Ok: Multi result, $TOTAL_VALUES values; ${#TEST_FIELD_NAMES[@]} values x $TEST_LINES results"
			else
				echo "-- Error: Multi result, $TOTAL_VALUES values, should be ${#TEST_FIELD_NAMES[@]} x $TEST_LINES"
				return 1
			fi
			
			# Write this test result to the Copytest gnuplot .dat file
			# Calculate the average since we have multiple results for this test
			# Calculate the error range
			echo "TEST \"$TEST_NAME\"" >> $PLOTDATA
			
			echo "--- Extracting, summing and averaging all field values"
			for f in ${!TEST_FIELD_NAMES[@]}
			do
				TEST_FIELD_NAME=${TEST_FIELD_NAMES[$f]}
				# Read *all* of the values for this test and sum them
				echo "--- Test: $TEST_NAME, Column: $f, Column Name: $TEST_FIELD_NAME"
				TEST_FIELD_AVERAGE=`get_test_average "$TEST_NAME" $f`
				TEST_FIELD_RANGE=`get_test_range "$TEST_NAME" $f`
				echo "\"$TEST_FIELD_NAME\" $TEST_FIELD_AVERAGE $TEST_FIELD_RANGE" >> $PLOTDATA
			done
			echo "" >> $PLOTDATA
			echo "" >> $PLOTDATA
		fi
	done
	
	# gnuplot instructions
	echo ""
	echo "Generating plot script..."
	echo "set terminal pngcairo enhanced font \"arial,12\" fontscale 1.0 size $CHART_X, $CHART_Y" >> $PLOTFILE
	echo "set colorbox vertical origin screen 0.9, 0.2 size screen 0.05, 0.6 front  noinvert bdefault" >> $PLOTFILE
	echo 'set key fixed right top vertical Right noreverse enhanced autotitle columnhead nobox' >> $PLOTFILE
	echo "set output '$CHART'"												>> $PLOTFILE
	echo 'set title "Copytest - Filesystem Benchmark Results"' 				>> $PLOTFILE
	echo 'set style data yerrorlines' 										>> $PLOTFILE
	echo 'set ylabel "MBytes/sec"' 											>> $PLOTFILE
	echo 'set xlabel "Copy method"' 										>> $PLOTFILE
	echo 'set yrange [0:*]' 												>> $PLOTFILE
	echo 'set xtics rotate'													>> $PLOTFILE
	echo 'set xtics norangelimit'											>> $PLOTFILE 
	echo 'set xtics ()'														>> $PLOTFILE
	echo 'set grid'															>> $PLOTFILE
	echo 'set trange [ * : * ] noreverse nowriteback'						>> $PLOTFILE
	echo 'set urange [ * : * ] noreverse nowriteback'						>> $PLOTFILE
	echo 'set vrange [ * : * ] noreverse nowriteback'						>> $PLOTFILE
	echo 'set xrange [ * : * ] noreverse writeback'							>> $PLOTFILE
	echo 'set x2range [ * : * ] noreverse writeback'						>> $PLOTFILE
	echo 'set y2range [ * : * ] noreverse writeback'						>> $PLOTFILE
	echo 'set zrange [ * : * ] noreverse writeback'							>> $PLOTFILE
	echo 'set cbrange [ * : * ] noreverse writeback'						>> $PLOTFILE
	echo 'set rrange [ * : * ] noreverse writeback'							>> $PLOTFILE
	echo 'I = {0.0, 1.0}'													>> $PLOTFILE
	echo 'NO_ANIMATION = 1'													>> $PLOTFILE
	# Each test needs to be a seperate plot
	for i in ${!TEST_NAMES[@]}
	do
		if [ "$i" = "0" ]
		then
			echo "plot '$PLOTDATA' using 0:2:3:xticlabel(1) index 0 lw 2 with yerrorlines,\\"	 		>> $PLOTFILE
			#echo "plot '$PLOTDATA' using 0:2:3:xticlabel(1) index 0 lw 2,\\"	 		>> $PLOTFILE
		else
			echo "     '' using 0:2:3:xticlabel(1) index $i lw 2 with yerrorlines,\\"	>> $PLOTFILE
			#echo "     '' using 0:2:3:xticlabel(1) index $i lw 2,\\"	 			>> $PLOTFILE
		fi
	done
	echo "- Ok"
	
	echo ""
	echo "==== Plot data ===="
	cat $PLOTDATA
	echo "EOF"
	echo "==== Plot file ===="
	cat $PLOTFILE
	echo "EOF"
	echo ""
	echo "Running gnuplot..."
	gnuplot < $PLOTFILE
	if [ "$?" = "0" ]
	then
		echo "- Ok"
	else
		echo "- Error: Call to gnuplot returned an error"
	fi
	
	echo ""
	echo "Cleaning up"
	echo "==========="
	rm -f -v $PLOTDATA
	rm -f -v $PLOTFILE
	echo ""
}

create_chart() {
	# Given a result CSV file, attempt to create charts using gnuplot
	echo "Start Chart Generation"
	echo "======================"
	
	if [ -s "$RESULTS" ]
	then
		echo "- Ok: Using '$RESULTS'"
		
		RESULTS_LINES=`cat $RESULTS | grep -v ^"Copy Task" | wc -l | awk '{print $1}'`
		if [ "$RESULTS_LINES" = "0" ]
		then
			echo "Error: No line(s) of testing result data found in '$RESULTS'"
			return 1
		else
			echo "- Ok: Found $RESULTS_LINES line(s) of testing result data"
			echo ""
			if [ "$RESULTS_LINES" = "1" ]
			then
				# One line of data
				create_chart_single
				
				echo "Attempting xdg-open of $CHART ..."
				xdg-open $CHART
				if [ "$?" = "0" ]
				then
					echo "- Ok"
				else
					echo "- Warning: Unable to open image viewer"
				fi
				echo ""
			else
				# Multiple lines of data
				create_chart_multi
				echo "Attempting xdg-open of $CHART ..."
				xdg-open $CHART
			fi
		fi
		
	else
		echo "Error: No CSV results file found"
		return 1
	fi
	
	echo ""
	echo "Chart completed - generated data in '$CHART'"
}

cleanup() {
	# Clear the test files
	echo "Cleaning Up"
	echo "==========="
	rm -v -f $SRC
	rm -v -f $DST
	echo ""
}

bw_test() {
	# $1 = name of test
	# $2 = SRC
	# $3 = DST
	TESTNAME="$1"
	
	if [ "$2" = "$3" ]
	then
		echo "Error: Source and destination cannot be the same directory."
		return 1
	fi
	
	SRC="$2/copytest.file"
	DST="$3/copytest.file"

	echo "Starting Test"
	echo "============="
	echo "- Test name: $TESTNAME"
	echo ""

	create_headers
	create_testfile

	# Record the size of the test file so that
	# all calculations are based on whatever file size
	# we are using
	echo "Benchmarks"
	echo "=========="
	echo "Benchmarking $TESTNAME ... please wait ... "
	SRC_BYTES=`ls -l $SRC | awk '{print $5}'`
	SRC_SIZE=`echo "$SRC_BYTES / 1024 / 1024" | bc`
	echo -n "$TESTNAME,$TESTDATE,$SRC_SIZE," >> $RESULTS

	#######################################################################
	# A basic test using 'cp'
	#######################################################################
	echo -n "- cp"
	SPEED=`{ time cp -f $SRC $DST >/dev/null 2>>$ERRORS; } 2>&1`
	if [ "$?" != "0" ]
    then
        echo ""
     	echo "- Error cp $SRC ..."
        cat $ERRORS
        return 1
    fi
	sleep $SLEEPTIME
	sync $DST
	rm -f $DST
	SPEED=`echo "$SRC_BYTES / $SPEED / 1024 / 1024" | bc`
	echo "		$SPEED MB/s"
	echo -n "$SPEED," >> $RESULTS

	#######################################################################
	# Using 'rsync'
	#######################################################################
	echo -n "- rsync"
	SPEED=`{ time rsync --inplace $SRC $DST >/dev/null 2>>$ERRORS; } 2>&1`
	if [ "$?" != "0" ]
    then
        echo ""
		echo "- Error rsync $SRC ..."
        cat $ERRORS
        return 1
    fi
	sleep $SLEEPTIME
	sync $DST
	rm -f $DST
	SPEED=`echo "$SRC_BYTES / $SPEED / 1024 / 1024" | bc`
	echo "		$SPEED MB/s"
	echo -n "$SPEED," >> $RESULTS

	#######################################################################
	# Using 'dd' with incrementally larger block sizes
	#######################################################################
	for BSIZE in "512" "8k" "16k" "32k" "64k" "128k" "256k" "512k" "1024k" "2048k" "4096k"
	do
		echo -n "- dd bs=${BSIZE}"
		rm -f $DST
	    SPEED=`{ time dd if=$SRC of=$DST bs=${BSIZE} 2>>$ERRORS; } 2>&1`
		if [ "$?" != "0" ]
        then
            echo ""
			echo "- Error dd bs=$BSIZE $SRC ..."
            cat $ERRORS
            return 1
        fi
		sleep $SLEEPTIME
		SPEED=`echo "$SRC_BYTES / $SPEED / 1024 / 1024" | bc`
		echo "	$SPEED MB/s"
		sync $DST
		echo -n "$SPEED," >> $RESULTS

	done

	# Terminate results file with final newline
	echo "" >> $RESULTS
	echo "- Ok"
	echo ""
	cleanup
	echo "Test completed - results in '$RESULTS'"
	
}

bw_chart() {
	if [ "$GNUPLOT" = "1" ]
	then
		create_chart	
	else
		echo "Error: gnuplot not found, unable to process result CSV data."
		return 1
	fi
}

help_text(){
	echo "You can now run your file transfer tests using the following syntax:"
	echo "bw_test NAME_OF_TEST /SRC_DIR /DEST_DIR"
	echo ""
	echo "For example:"
	echo "$ bw_test TMP_to_VAR /tmp /var"
	echo "Your results will be captured in '$RESULTS'"
	echo ""
	echo "You can chart any data in '$RESULTS' with bw_chart, for example:"
	echo "$ bw_chart"
	echo "Your chart will be created as '$CHART'"
}

if [ "$SOURCED" = "1" ]
then
	echo "Copytest - A simple file copy transfer speed testing tool"
	echo
	echo "Checking for tools"
	echo "=================="
	for tool in cp rsync dd bc
	do
		which $tool
		if [ "$?" = "1" ]
		then
			echo "ERROR: $tool not found"
			return 1
		fi
	done
	which gnuplot
	if [ "$?" = "1" ]
	then
		echo "WARN: gnuplot not found - no chart output available"
		export GNUPLOT=0
	else
		export GNUPLOT=1
	fi
	echo ""
	help_text
else
	echo "Copytest - A simple file copy transfer speed testing tool"
	echo
	echo "You need to 'source' this file first."
	echo "For example:"
	echo "$ source $0"
fi